### ISSUE TITLE
Can't install with bower

### ISSUE THREAD

**Issue by pr00thmatic** [eu81273/angular.panels#1]
hi! I wanted to use your module, but I couldn't install it with bower.

Here is my bower file: 

`{
  "name": "un-nombre",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.3.0",
    "bootstrap-sass-official": "^3.2.0",
    "angular-animate": "^1.3.0",
    "angular-cookies": "^1.3.0",
    "angular-resource": "^1.3.0",
    "angular-route": "^1.3.0",
    "angular-sanitize": "^1.3.0",
    "angular-touch": "^1.3.0",
    "angular-carousel": "~0.3.10",
    "angular.panels": "https://github.com/eu81273/angular.panels.git"
  },
  "devDependencies": {
    "angular-mocks": "^1.3.0"
  },
  "appPath": "app",
  "moduleName": "unNombreApp"
}`

and the error is

`Additional error details:
Unexpected token ]`

I hope you can fix this, because I really liked your module @.@

**Comment by eu81273** [comment]
@VengadoraVG 
Hi!  I just update the bower.json file. Thank you.
