### ISSUE TITLE
Cannot use templateCache with bower

### ISSUE THREAD

**Issue by hrnn** [eu81273/angular.panels#10]
As part #7 templateCache support was added, but files under _dist_ are outdated, could you generate them with the latest changes and publish 1.0.4 it is required to use it with bower, Thank you.

**Comment by nulayuhz** [comment]
same issue, Thank you.

**Comment by PatrykTucki** [comment]
+1

**Comment by hrnn** [comment]
https://github.com/hrnn/angular.panels
